[package]
name = "exampleapp"
version = "0.1.0"
authors = ["Hamza"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "^0.2"
yew = "0.17"
mat-web-comp = { path = ".." }
