[package]
authors = ["Hamza"]
edition = "2018"
name = "yew-material-components"
version = "0.1.0"

[dependencies]
wasm-bindgen = "^0.2"
yew = { git = "https://github.com/yewstack/yew/", branch = "master" }
js-sys = "0.3"
web-sys = { version = "0.3", features = ["ValidityState", "CustomEvent"] }
