use_field_init_shorthand = true
#Nightly only below, don't know why i even added those
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_matchers = true
wrap_comments = true
