name: Lint
on:
    push:
        branches: [ master ]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions-rs/toolchain@v1
                with:
                    toolchain: nightly
                    target: wasm32-unknown-unknown
                    override: true

            -   uses: actions/cache@v2
                with:
                    path: |
                        ~/.cargo/registry
                        ~/.cargo/git
                        target
                    key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}
                    restore-keys: |
                        cargo-${{ runner.os }}-

            -   name: Run rustfmt
                run: cargo fmt -- --check
